using GestaoClientes.Domain.Entities; using GestaoClientes.Domain.Enums; using GestaoClientes.Domain.Repositories; using Microsoft.EntityFrameworkCore;
namespace GestaoClientes.Infrastructure;
public sealed class GestaoClientesDbContext(DbContextOptions<GestaoClientesDbContext> options):DbContext(options)
{
    public DbSet<Cliente> Clientes => Set<Cliente>();
    public DbSet<Endereco> Enderecos => Set<Endereco>();
    protected override void OnModelCreating(ModelBuilder builder) => builder.ApplyConfigurationsFromAssembly(typeof(GestaoClientesDbContext).Assembly);
}
public sealed class ClienteRepository(GestaoClientesDbContext db):IClienteRepository { public Task<bool> CpfExisteAsync(string cpf,int? id=null)=>db.Clientes.AnyAsync(x=>x.Cpf==cpf&&(!id.HasValue||x.Id!=id)); public Task<bool> EmailExisteAsync(string email,int? id=null)=>db.Clientes.AnyAsync(x=>x.Email==email&&(!id.HasValue||x.Id!=id)); public Task<Cliente?> ObterAsync(int id)=>db.Clientes.Include(x=>x.Enderecos).SingleOrDefaultAsync(x=>x.Id==id); public async Task<(IReadOnlyList<Cliente>,int)> ListarAsync(int pagina,int tamanho,string? nome,string? cpf,StatusCliente? status){var q=db.Clientes.Include(x=>x.Enderecos).AsQueryable();if(!string.IsNullOrWhiteSpace(nome))q=q.Where(x=>x.Nome.Contains(nome));if(!string.IsNullOrWhiteSpace(cpf))q=q.Where(x=>x.Cpf.Contains(cpf));q=q.Where(x=>x.Status==(status??StatusCliente.Ativo));var total=await q.CountAsync();return(await q.OrderBy(x=>x.Nome).Skip((pagina-1)*tamanho).Take(tamanho).ToListAsync(),total);} public Task AdicionarAsync(Cliente c)=>db.Clientes.AddAsync(c).AsTask(); }
public sealed class UnitOfWork(GestaoClientesDbContext db) : IUnitOfWork { public Task SalvarAsync() => db.SaveChangesAsync(); }
public static class Seeder { public static async Task SemearAsync(GestaoClientesDbContext db){await db.Database.MigrateAsync();if(await db.Clientes.AnyAsync())return;var dados=new[]{("Maria Silva","52998224725","maria@exemplo.com"),("João Santos","11144477735","joao@exemplo.com"),("Ana Costa","93541134780","ana@exemplo.com")};foreach(var d in dados)db.Clientes.Add(new Cliente(d.Item1,d.Item2,d.Item3,"11999999999",new DateOnly(1990,1,1),new Endereco("01001000","Praça da Sé","100",null,"Sé","São Paulo","SP",true)));await db.SaveChangesAsync();} }
